INSERT INTO properties (user_id, title, description, price, price_label, type, transaction, surface, rooms, bathrooms, city, neighborhood, features, tags, video_url, thumbnail, music_title, music_artist, status, views, likes_count, comments_count, saves_count, shares_count) VALUES
(2, 'Villa luxueuse a Cocody Angre', 'Superbe villa de standing avec piscine, jardin tropical et vue imprenable. Quartier residentiel calme, proche de toutes les commodites. Sejour double, cuisine equipee, 4 chambres climatisées.', 250000000, '250 M FCFA', 'villa', 'vente', 450, 4, 3, 'Abidjan', 'Cocody Angre', '["Piscine","Jardin","Climatisation","Garage","Cuisine equipee","Videosurveillance"]', '["luxe","piscine","cocody","villa"]', 'uploads/videos/demo1.mp4', NULL, 'Sunset Dreams', 'Kanda Bongo Man', 'active', 1520, 45, 12, 89, 34),
(2, 'Appartement moderne au Plateau', 'Bel appartement entierement renove au coeur du Plateau, ideal pour cadre expatrie. Vue panoramique sur la lagune, prestations haut de gamme.', 85000000, '85 M FCFA', 'appartement', 'vente', 120, 3, 2, 'Abidjan', 'Plateau', '["Vue lagune","Climatisation","Securite","Parking","Ascenseur"]', '["plateau","moderne","appartement","centre-ville"]', 'uploads/videos/demo2.mp4', NULL, 'City Lights', 'DJ Arafat', 'active', 890, 23, 8, 45, 12),
(3, 'Studio meuble - Zone 4', 'Studio tout equipe dans residence securisee a Marcory Zone 4. Parfait pour etudiant ou jeune professionnel. Proche commerces et transports.', 25000000, '25 M FCFA', 'studio', 'vente', 35, 1, 1, 'Abidjan', 'Marcory Zone 4', '["Meuble","Climatisation","Securite","Internet"]', '["studio","marcory","investissement","meuble"]', 'uploads/videos/demo3.mp4', NULL, 'Petit a petit', 'Magic System', 'active', 2340, 67, 21, 120, 56),
(2, 'Terrain a batir - Riviera 3', 'Magnifique terrain plat de 600 m2 dans lotissement viabilise. Titre foncier, tous reseaux. Ideal pour construction villa.', 60000000, '60 M FCFA', 'terrain', 'vente', 600, 0, 0, 'Abidjan', 'Riviera 3', '["Titre foncier","Viabilise","Cloture","Eau","Electricite"]', '["terrain","riviera","construction","investissement"]', 'uploads/videos/demo4.mp4', NULL, 'Africa', 'Youssoupha', 'active', 670, 15, 5, 34, 8),
(4, 'Villa avec piscine - Grand-Bassam', 'Superbe villa de vacances a 20min d Abidjan. Piscine, grand jardin, 3 chambres. Ideal residence secondaire ou location saisonniere.', 120000000, '120 M FCFA', 'villa', 'vente', 350, 3, 2, 'Grand-Bassam', 'Moossou', '["Piscine","Jardin","Proche plage","Climatisation","Garage"]', '["bassam","villa","vacances","piscine"]', 'uploads/videos/demo5.mp4', NULL, 'La vie est belle', 'Serge Beynaud', 'active', 1890, 52, 18, 76, 29),
(5, 'Appartement a louer - Deux-Plateaux', 'Appartement lumineux en location, 2 chambres, salon, cuisine americaine. Disponible immediatement. Charges comprises.', 350000, '350 000 FCFA/mois', 'appartement', 'location', 80, 2, 1, 'Abidjan', 'Deux-Plateaux', '["Cuisine americaine","Climatisation","Eclairage naturel","Proche ecoles"]', '["location","deux-plateaux","appartement","famille"]', 'uploads/videos/demo1.mp4', NULL, 'Douce nuit', 'Didieri', 'active', 3100, 78, 25, 145, 67),
(3, 'Bureau equipe - Zone 4', 'Espace bureau de 50 m2 dans immeuble moderne. Parfait pour startup ou PME. Salle de reunion partagee, fibre optique.', 200000, '200 000 FCFA/mois', 'bureau', 'location', 50, 0, 1, 'Abidjan', 'Marcory Zone 4', '["Fibre optique","Climatisation","Salle reunion","Securite 24/7","Parking"]', '["bureau","professionnel","startup","zone4"]', 'uploads/videos/demo2.mp4', NULL, 'Work Hard', 'Kiff No Beat', 'active', 430, 11, 4, 23, 5),
(2, 'Commerce - Rue Princesse', 'Local commercial de 100 m2 sur rue passante au coeur de Cocody. Tres forte affluence, ideal pour restaurant, boutique ou agence.', 150000000, '150 M FCFA', 'commerce', 'vente', 100, 0, 1, 'Abidjan', 'Cocody Rue Princesse', '["Vitrine","Climatisation","Double vitrage","Alarme"]', '["commerce","cocody","local","investissement"]', 'uploads/videos/demo3.mp4', NULL, 'Business', 'Kaaris', 'active', 1120, 34, 9, 56, 18),
(4, 'Terrain viabilise - Bingerville', 'Terrain de 400 m2 dans nouveau lotissement a Bingerville. Prix attractif, ideal construction villa moderne. Proche universite.', 35000000, '35 M FCFA', 'terrain', 'vente', 400, 0, 0, 'Bingerville', 'Carrefour', '["Titre foncier","Viabilise","Ecole","Marche"]', '["bingerville","terrain","pas cher","investissement"]', 'uploads/videos/demo4.mp4', NULL, 'Petit pays', 'Cesaria Evora', 'active', 540, 19, 6, 28, 7),
(5, 'Studio pas cher - Yopougon', 'Studio economique a Yopougon Sicogi. Ideal premier investissement locatif. Faible budget, fort rendement. Loue 150 000 FCFA/mois.', 15000000, '15 M FCFA', 'studio', 'vente', 28, 1, 1, 'Abidjan', 'Yopougon Sicogi', '["Rentable","Loue","Faible budget","Proche transports"]', '["yopougon","investissement","rentable","premier achat"]', 'uploads/videos/demo5.mp4', NULL, 'Chicot', 'Dj Leo', 'active', 2780, 89, 31, 167, 78);
