/**
 * Configuration de navigation du portail entreprise
 */
export const navigation = [
    {
        id: 'overview',
        label: 'Vue globale',
        items: [
            {
                name: 'dashboard.master',
                label: 'Tableau de bord',
                icon: 'layout-dashboard',
                badge: null,
            },
        ],
    },
    {
        id: 'management',
        label: 'Gestion',
        items: [
            {
                id: 'immobilier',
                label: 'Immobilier',
                icon: 'building',
                accent: 'emerald',
                badgeKey: 'immobilier',
                children: [
                    { name: 'immobilier.index', label: "Vue d'ensemble" },
                    { name: 'dashboard.agencies', label: 'Agences' },
                    { name: 'immobilier.batiments', label: 'Bâtiments' },
                    { name: 'immobilier.logements', label: 'Logements' },
                    { name: 'immobilier.illustrations', label: 'Illustrations' },
                    { name: 'immobilier.affectations', label: 'Affectation des logements' },
                    { name: 'immobilier.contrats', label: 'Contrats de bail' },
                    { name: 'immobilier.locataires', label: 'Locataires' },
                    { name: 'immobilier.factures', label: 'Facturation' },
                    { name: 'immobilier.paiements', label: 'Paiements de loyer' },
                    { name: 'immobilier.renouvellements', label: 'Renouvellements' },
                    { name: 'immobilier.engagements', label: 'Engagements' },
                    { name: 'immobilier.etats-des-lieux', label: 'États des lieux' },
                    { name: 'immobilier.historique', label: 'Historique' },
                ],
            },
            {
                id: 'hotel',
                label: 'Hôtellerie',
                icon: 'hotel',
                accent: 'amber',
                badgeKey: 'hotel',
                blocked: true,
                children: [
                    { name: 'dashboard.hotel', label: "Vue d'ensemble" },
                    { name: 'hotel.reservations', label: 'Réservations' },
                    { name: 'hotel.checkinout', label: 'Check-in / out' },
                    { name: 'hotel.chambres', label: 'Chambres' },
                    { name: 'hotel.clients', label: 'Clients' },
                    { name: 'hotel.services', label: 'Services' },
                    { name: 'hotel.nettoyage', label: 'Nettoyage' },
                    { name: 'hotel.tarifs', label: 'Tarifs' },
                    { name: 'hotel.personnel', label: 'Personnel' },
                    { name: 'hotel.equipements', label: 'Équipements' },
                ],
            },
        ],
    },
    {
        id: 'modules',
        label: 'Modules',
        items: [
            {
                id: 'accounting',
                label: 'Comptabilité',
                icon: 'calculator',
                accent: 'violet',
                children: [
                    { name: 'dashboard.accounting', label: 'Vue d\'ensemble' },
                    { name: 'accounting.facture-creation', label: 'Créer une facture' },
                ],
            },
            { name: 'dashboard.maintenance', label: 'Maintenance', icon: 'wrench', accent: 'orange', badgeKey: 'maintenance' },
            { name: 'dashboard.reports', label: 'Rapports', icon: 'chart', accent: 'cyan' },
            { name: 'dashboard.maps', label: 'Cartographie', icon: 'map', accent: 'indigo' },
            { name: 'dashboard.roles', label: 'Rôles & permissions', icon: 'shield', accent: 'rose' },
        ],
    },
];

export const routeTitles = {
    'dashboard.master': 'Tableau de bord',
    'immobilier.index': 'Gestion immobilière',
    'immobilier.factures': 'Facturation des loyers',
    'immobilier.paiements': 'Paiements de loyer',
    'dashboard.agencies': 'Gestion des agences',
    'dashboard.agency.create': 'Nouvelle agence',
    'dashboard.agency.show': "Détail de l'agence",
    'dashboard.agency.edit': "Modifier l'agence",
    'immobilier.batiments': 'Gestion des bâtiments',
    'immobilier.logements': 'Gestion des logements',
    'immobilier.illustrations': 'Gestion des illustrations',
    'immobilier.affectations': 'Affectation des logements',
    'immobilier.contrats': 'Contrats de bail',
    'immobilier.locataires': 'Gestion des locataires',
    'immobilier.renouvellements': 'Renouvellements de contrat',
    'immobilier.engagements': 'Engagements',
    'immobilier.etats-des-lieux': 'États des lieux',
    'immobilier.historique': 'Historique immobilier',
    'dashboard.hotel': 'Gestion hôtelière',
    'hotel.reservations': 'Réservations',
    'hotel.checkinout': 'Check-in / Check-out',
    'hotel.chambres': 'Gestion des chambres',
    'hotel.clients': 'Gestion des clients',
    'hotel.services': 'Services hôteliers',
    'hotel.nettoyage': 'Nettoyage',
    'hotel.tarifs': 'Tarifs',
    'hotel.personnel': 'Personnel',
    'hotel.equipements': 'Équipements',
    'dashboard.accounting': 'Comptabilité & facturation',
    'accounting.facture-creation': 'Création de facture',
    'dashboard.maintenance': 'Maintenance / SAV',
    'dashboard.reports': 'Rapports & statistiques',
    'dashboard.maps': 'Cartographie',
    'dashboard.roles': 'Rôles & permissions',
};
